# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # RtD seems to be not happy with pdm installs,
      # hence use pip directly instead.
      - python -m pip install -r requirements-docs-locked.txt
      - python -m pip list
    pre_build:
      - pip install --no-deps .

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
