name: Release

on:
  push:
    tags: ['v*']

defaults:
  run:
    shell: bash

jobs:
  draft-release:
    name: Create draft release
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.8.8"
          python-version: ${{ matrix.python-version }}
      - name: Add version to environment
        run: |
          PROJECT_VERSION=`sed -ne 's/^version = "\([0-9\.]*\)"/\1/p' pyproject.toml`
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      - name: Build package for PyPI
        run: |
          uv run python scripts/add-locked-targets-to-pyproject-toml.py
          uv build
          # Just in case, undo the changes to `pyproject.toml`
          git restore --staged . && git restore .
      - name: Generate Release Notes
        run: |
          echo "" >> ".github/release_template.md"
          echo "## Changelog" >> ".github/release_template.md"
          echo "" >> ".github/release_template.md"
          uv add typer
          uv run python scripts/changelog-to-release-template.py >> ".github/release_template.md"
          echo "" >> ".github/release_template.md"
          echo "## Changes" >> ".github/release_template.md"
          echo "" >> ".github/release_template.md"
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty='format:* %h %s' --no-merges >> ".github/release_template.md"
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          body_path: ".github/release_template.md"
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          draft: true
          files: |
            dist/openscm_units-${{ env.PROJECT_VERSION }}-py3-none-any.whl
            dist/openscm_units-${{ env.PROJECT_VERSION }}.tar.gz
